## Load all functions

source("./source/condition_builder.R")
source("./source/data_subsetting_plot.R")
source("./source/data_subsetting_boxplot.R")
source("./source/list_simulations.R")
source("./source/get_data.R")
source("./source/summary_stats.R")
source("./source/ts_decompose.R")
source('./source/ts_trend_IDbest.R')
source("./source/ts_test.R")
source("./source/add_alpha.R")
source("./source/distribution_plot.R")
source("./source/HC_plot.R")
source("./source/ratio-expno_boxplot.R")
source("./source/TL_plot.R")
source("./source/get_dataInd.R")
source("./source/comp_boxplot.r")
source('./source/boot_resamp.r')
source("./source/data_barplot.R")
